name: Simple Text
description: You found a bug
labels: [bug]
assignees: DevDyna
body:
  - type: checkboxes
    id: check-base
    attributes:
      label: Check Base
      description: base-desc
      options:
        - label: 1-label required
          required: true
        - label: 2-label required
          required: true

  - type: dropdown
    id: list-selection
    attributes:
      label: List Selection
      description: list-desc
      options:
        - 0
        - 1
        - 2
    validations:
      required: true
        
  - type: input
    id: text-box
    attributes:
      label: Text Box
      placeholder: example
      description: desc-box
    validations:
      required: true

  - type: textarea
    id: large-text-box
    attributes:
      label: Large Text Box
      description: desc-large-box
      placeholder: example
    validations:
      required: true
      
